// <auto-generated />
using System;
using AssetWithDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetWithDB.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221218155301_SeedingDeviceData")]
    partial class SeedingDeviceData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssetWithDB.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("LocalPrice")
                        .HasColumnType("float");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TypeOfDevice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "HP",
                            Currency = "SEK",
                            LocalPrice = 1000.0,
                            Model = "Elite Dragonfly G2",
                            Office = "Stockholm",
                            Price = 9000,
                            PurchaseDate = new DateTime(2021, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfDevice = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Iphone",
                            Currency = "EUR",
                            LocalPrice = 1300.0,
                            Model = "13 pro max",
                            Office = "Berlin",
                            Price = 13000,
                            PurchaseDate = new DateTime(2021, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfDevice = "Phone"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Samsung",
                            Currency = "SEK",
                            LocalPrice = 11000.0,
                            Model = "S22",
                            Office = "New York",
                            Price = 11000,
                            PurchaseDate = new DateTime(2022, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TypeOfDevice = "Phone"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
